### ISSUE TITLE
Icon Requests

### ISSUE THREAD

**Issue by TheTechnologyStudio** [JonSn0w/Atom-FileType-Icons#1]
Hello, i have some requests for the atom file icons package, Can you add .exe and maybe a minecraft icon that has the same style as ur current atom icons. Thanks.

**Comment by tterb** [comment]
Yeah, when I get a chance I'll create a .exe file icon and add it to the collection. As for the Minecraft icon, is there a specific file-type that you'd like the icon to be for?   
Otherwise, I don't know that it would necessarily fit the intentions of the collection, though I'd be happy to provide you with the resources to create the icon on your own.

**Comment by tterb** [comment]
The .exe icon has been added in [v1.2](https://github.com/JonSn0w/Atom-File-Icons/tree/v1.2)
